// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.1.1

//# unitInfo: Provides: Expect_test_config
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function return$0(x){return x;}
   function bind(t, f){return caml_call1(f, t);}
   function to_run(t){return t;}
   var IO_flush = [0, return$0, bind, to_run];
   function sanitize(s){return s;}
   function run(f){return caml_call1(f, 0);}
   function flushed(param){return 1;}
   var Expect_test_config = [0, [0], IO_flush, run, flushed, sanitize, 15023];
   runtime.caml_register_global(0, Expect_test_config, "Expect_test_config");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJleHBlY3RfdGVzdF9jb25maWcuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbInJldHVybiQwIiwieCIsImJpbmQiLCJ0IiwiZiIsInRvX3J1biIsInNhbml0aXplIiwicyIsInJ1biIsImZsdXNoZWQiXSwic291cmNlcyI6WyIvaG9tZS9uYXRoYW4vLm9wYW0vZGVmYXVsdC9saWIvcHB4X2V4cGVjdC9jb25maWcvZXhwZWN0X3Rlc3RfY29uZmlnLm1sIl0sIm1hcHBpbmdzIjoiOzs7Ozs7OztHOzs7OztZQUdNQSxTQUFPQyxHQUFJLE9BQUpBLEVBQUs7WUFDWkMsS0FBS0MsR0FBR0MsR0FBSSxrQkFBSkEsR0FBSEQsR0FBVTtZQU1mRSxPQUFPRixHQUFJLE9BQUpBLEVBQUs7R0FIQSxtQkFKWkgsVUFDQUUsTUFNQUc7WUFHRkMsU0FBU0MsR0FBSSxPQUFKQSxFQUFLO1lBQ2RDLElBQUlKLEdBQUksa0JBQUpBLE1BQVE7WUFDWkssZUFBYSxTQUFJOytDQURqQkQsS0FDQUMsU0FGQUg7OztFIiwic291cmNlc0NvbnRlbnQiOlsibW9kdWxlIElPX3J1biA9IHN0cnVjdFxuICB0eXBlICdhIHQgPSAnYVxuXG4gIGxldCByZXR1cm4geCA9IHhcbiAgbGV0IGJpbmQgdCB+ZiA9IGYgdFxuZW5kXG5cbm1vZHVsZSBJT19mbHVzaCA9IHN0cnVjdFxuICBpbmNsdWRlIElPX3J1blxuXG4gIGxldCB0b19ydW4gdCA9IHRcbmVuZFxuXG5sZXQgc2FuaXRpemUgcyA9IHNcbmxldCBydW4gZiA9IGYgKClcbmxldCBmbHVzaGVkICgpID0gdHJ1ZSAoKiB0aGUgcnVudGltZSBmbHVzaGVkIFtzdGRvdXRdIGJlZm9yZSBjYWxsaW5nIHRoaXMgZnVuY3Rpb24gKilcblxubGV0IHVwb25fdW5yZWxlYXNhYmxlX2lzc3VlID0gYENSXG4iXX0=
